version: "3"

services:
  consul:
    image: soai_consul:latest
    container_name: soai_consul
    build:
      context: ./backend/services/consul
      dockerfile: ./Dockerfile
    ports:
      - "8500:8500"  # Consul Web UI
      - "8600:8600/udp"
    command: "agent -server -bootstrap -ui -client=0.0.0.0"
    restart: always
    networks:
      - soai-net
  chatbot:
    container_name: soai_chatbot
    image: soai_chatbot:latest
    build:
      context: ./backend/services/chatbot
      dockerfile: ./Dockerfile
    environment:
      - CONSUL_HOST=consul
      - SERVICE_NAME=chatbot-service
      - SERVICE_PORT=8000
    restart: always
    networks:
      - soai-net
    volumes:
      - ./backend/services/chatbot/app:/app

  nginx:
    container_name: soai_nginx
    image: soai_nginx:latest
    build:
      context: ./backend/services/webserver
      dockerfile: ./Dockerfile
    restart: always
    networks:
      - soai-net
    ports:
      - "443:443"
    volumes:
      - nginx_conf:/etc/nginx/ssl/certs

  ollama:
    container_name: soai_ollama
    image: soai_ollama:latest
    build:
      context: ./backend/services/ollama
    networks:
      - soai-net
    volumes:
      - ollama:/root/.ollama

volumes:
  nginx_conf:
  ollama:

networks:
  soai-net:
    driver: bridge
    ipam:
      driver: default
