apiVersion: v2
name: otel-collector
description: OpenTelemetry Collector - a vendor-agnostic service for receiving, processing, and exporting telemetry data.
type: application
version: 1.0.0
appVersion: "0.74.0"