# global:
#   security:
#     tls:
#       enabled: true
otel:
  image: otel/opentelemetry-collector-contrib:latest
  clickHouse:
    enabled: true
  prometheus:
    enabled: true
    scrapeConfigs:
      scrapeInterval: 15s
      scrapeTimeout: 10s
      evaluationInterval: 1m
      fallbackScrapeProtocol: true
      jobs:
        pod:
          enabled: true
        service:
          enabled: true
        endpoint:
          enabled: true
  resource:
    requests:
      cpu: "200m"
      memory: "256Mi"
    limits:
      cpu: "1"
      memory: "1Gi"