apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-alert-rules
  namespace: {{ .Values.global.namespace }}
data:
  alert.rules.yml: |
{{ .Files.Get "alert-rules/alert.rules.yml" | indent 4 }}
