{{- if .Values.prometheus.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-pvc
  namespace: {{ .Values.global.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.prometheus.persistence.storageClass }}
  resources:
    requests:
      storage: {{ .Values.prometheus.persistence.size }}
---
{{- end }}
{{- if .Values.grafana.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-pvc
  namespace: {{ .Values.global.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.grafana.persistence.storageClass }}
  resources:
    requests:
      storage: {{ .Values.grafana.persistence.size }}
{{- end }}
