apiVersion: v1
kind: Service
metadata:
  name: {{ template "clickhouse.name" . }}
spec:
  selector: {{- include "clickhouse.selectorLabels" . | nindent 4 }}
  ports:
  - port: 9000
    name: http
    targetPort: 9000
    protocol: TCP
  - port: 8123
    name: http-it
    targetPort: 8123
    protocol: TCP